{
  "comments": [
    {
      "unresolved": true,
      "key": {
        "uuid": "5d05f30c_f676cf5d",
        "filename": "yaml/xyz/openbmc_project/Control/Failover.interface.yaml",
        "patchSetId": 2
      },
      "lineNbr": 12,
      "author": {
        "id": 1000004
      },
      "writtenOn": "2025-09-30T18:28:44Z",
      "side": 1,
      "message": "This (maybe purposely) seems pretty open ended? Is it the application on the BMC that is requesting it? An external entity? Could it be an error log ID? Or is it the user (root, admin, ...)?",
      "revId": "29a8674cb64dec2864939915fdd77aa807400c7b",
      "serverId": "adbd0a64-1f21-4d83-b585-671fe73cb6e4"
    }
  ]
}