{
  "comments": [
    {
      "unresolved": true,
      "key": {
        "uuid": "b9e86c56_fa318135",
        "filename": "yaml/xyz/openbmc_project/Control/SyncBMCData.interface.yaml",
        "patchSetId": 5
      },
      "lineNbr": 33,
      "author": {
        "id": 1000008
      },
      "writtenOn": "2025-01-28T15:20:39Z",
      "side": 1,
      "message": "if someone tried to start a full sync and the network was down, how would that show up?",
      "revId": "c8573e6214c1b1124d6578fd3317dec05e1e7ddd",
      "serverId": "adbd0a64-1f21-4d83-b585-671fe73cb6e4"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "7272e004_62b40dfd",
        "filename": "yaml/xyz/openbmc_project/Control/SyncBMCData.interface.yaml",
        "patchSetId": 5
      },
      "lineNbr": 33,
      "author": {
        "id": 1001992
      },
      "writtenOn": "2025-01-30T08:46:19Z",
      "side": 1,
      "message": "Do you mean, before starting a full sync, or after starting?\nBefore starting: we would indicate that the sibling is not available.\nAfter starting: the exact reason for the failure would be unclear (as concurrent process, though some data may still pass). To address this, added a \"FullSyncFailed\" status. This status allows us to identify that some data may have failed during the sync process.",
      "parentUuid": "b9e86c56_fa318135",
      "revId": "c8573e6214c1b1124d6578fd3317dec05e1e7ddd",
      "serverId": "adbd0a64-1f21-4d83-b585-671fe73cb6e4"
    }
  ]
}